cp -fr ~/.config/hypr .config/
cp -fr ~/.config/kitty .config/
cp -fr ~/.config/ranger .config/
cp -fr ~/.config/swaync .config/
cp -fr ~/.config/waybar .config/
cp -fr ~/.config/wlogout .config/
cp -fr ~/.config/mimeapps.list .config
cp -frp ~/.oh-my-zsh/custom .oh-my-zsh/custom
cp -fr ~/.z* .
